name = "Psikolera"
author = "kodiitulip"
version = "2.2.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4879d5b075c59d574553b092fc0f8696d72d4f50c2e57883b2635206006b48a6"

[versions]
fabric = "0.18.4"
minecraft = "1.21.11"