name = "Psikolera"
author = "kodiitulip"
version = "2.2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ab06952fd402218ce237bcaccc7798c7c851a8285a13bbebe30751052215ca34"

[versions]
fabric = "0.18.4"
minecraft = "1.21.11"
