name = "Psikolera"
author = "kodiitulip"
version = "1.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "45a47ce933215afa82d1be4eacccac6a583218fc22fae4f41c079da1c8553051"

[versions]
fabric = "0.18.4"
minecraft = "1.21.11"
